### ISSUE TITLE
 【第二期】技术分享的主题讨论

### ISSUE THREAD

**Issue by hanks-zyh** [xitu/Learning-Sharing#2]
按照初步计划是介绍slack的使用，大家有其他意向的话可以进行讨论
1. slack的基本使用
2. slack的高级玩法

[**IFTTT** : Connect Slack to hundreds of apps - ](https://ifttt.com/slack)

Get the most out of Slack by connecting it to Gmail, Twitter, Google Calendar, Weather, Pocket and hundreds of your favorite apps and devices.

**Comment by kalasoo** [comment]
Cool，这里大家可以先找一些相关的工具，尤其是和各自开发相关，或者我们产品运营相关的需求相关的。这样，我们可以定点来思考有哪些工具可以放到我们的具体工作当中

**Comment by hanks-zyh** [comment]
目的是希望能用户工具达到提高效率
